dist: bionic

language:
  - php
  - node_js

node_js:
  - node

services:
  - mysql

env:
  global:
    - WP_VERSION=latest

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=4.7.6
      dist: precise
      before_install: nvm install --lts
    - php: 5.3
      dist: precise
      before_install: nvm install --lts
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: WP_VERSION=nightly
    - php: 7.3
  fast_finish: true

branches:
  only:
    - master
    - dev

install:
  - npm install
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost "$WP_VERSION"

script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - composer lint
  - composer test
  - composer test-multisite
  - npm test -- --wp="$WP_VERSION"

cache:
  npm: true
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
