language: php

env:
  global:
	- WP_VERSION=latest

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=4.7.6
      dist: precise
    - php: 5.3
      env: WP_VERSION=latest
      dist: precise
    - php: 5.6
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=nightly
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
	  env: WP_VERSION=latest
	- php: 7.3
      env: WP_VERSION=latest
  fast_finish: true

branches:
  only:
    - master
    - dev

install:
  - npm install
  - composer install

  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
  - phpenv config-rm xdebug.ini || echo "Xdebug not available"
  - phpenv rehash

  - bash bin/install-wp-tests.sh wordpress_test root '' localhost "$WP_VERSION"

script:
  - find . -path ./vendor -prune -o -type "f" -iname "*.php" | xargs -L "1" php -l
  - composer lint
  - composer test
  - composer test-multisite
  - npm test -- --wp="$WP_VERSION"
